<html>
<title>Broken Model Boardgamegeek Stats</title>
<link href="$app_root$/../stylesheets/style.css" rel="stylesheet" type="text/css">
<script src="$app_root$/../js/jquery-1.4.2.min.js"></script>
<script src="$app_root$/../js/bgg.js"></script>
<body>

<div id="header_nav">
 <a href="$app_root$/game_correlations">Games</a>
 <a href="$app_root$/user_correlations_list">Geeks</a>
 <a href="$app_root$/about">About</a>
</div>