$ views/header() $

<div class="text_section">

<p>
<a href="$app_root$/game_correlations">Games</a><br/>
List of correlated games - find a game, discover related games.
</p>

<p>
<a href="$app_root$/user_correlations_list">Geeks</a><br/>
List of correlated users - find your name, discover similar geeks, get recommendations.
<p>

<p>
<a href="$app_root$/about">About</a><br/>
Read more about this site.
</p>

</div>

$ views/footer() $